<?php

namespace Database\Seeders;

use App\Models\Contacto;
use App\Models\EtapaTramite;
use App\Models\Expediente;
use App\Models\TipoTramite;
use App\Models\User;
use Illuminate\Database\Seeder;

class ExpedienteSeeder extends Seeder
{
    public function run(): void
    {
        $asesores = User::role('asesor')->pluck('id')->toArray();

        if (empty($asesores)) {
            $this->command->warn('No hay asesores. Corre AsesorSeeder primero.');
            return;
        }

        // Obtener tipos y sus etapas
        $fovissste  = TipoTramite::where('slug', 'fovissste')->first();
        $infonavit  = TipoTramite::where('slug', 'infonavit')->first();
        $combo      = TipoTramite::where('slug', 'fovissste-infonavit')->first();
        $avaluo     = TipoTramite::where('slug', 'avaluo')->first();
        $escrituras = TipoTramite::where('slug', 'escrituras')->first();

        // Map: tipo_tramite_id => [etapa_ids en orden]
        $etapasMap = [];
        foreach ([$fovissste, $infonavit, $combo, $avaluo, $escrituras] as $tipo) {
            if ($tipo) {
                $etapasMap[$tipo->id] = EtapaTramite::where('tipo_tramite_id', $tipo->id)
                    ->orderBy('orden')->pluck('id')->toArray();
            }
        }

        $estados = ['en_proceso', 'en_proceso', 'en_proceso', 'pausado', 'aprobado', 'firmado', 'cerrado'];
        $usosCredito = ['retiro_directo', 'compraventa', 'retiro_directo', 'retiro_directo'];

        $expedientesData = [
            // FOVISSSTE
            [
                'tipo' => $fovissste,  'etapa_idx' => 0,
                'acreditado_nombre' => 'Arturo Salinas Pérez',
                'acreditado_curp'   => 'SAPA780312HDFRLR05',
                'acreditado_rfc'    => 'SAPA780312AB3',
                'acreditado_telefono' => '7711234567',
                'acreditado_email'  => 'arturo.salinas@gmail.com',
                'acreditado_municipio' => 'Pachuca',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42000',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => 12,
                'vendedor_nombre'   => 'Rosa María Salinas',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Av. Juárez',
                'vivienda_numero'   => '45',
                'vivienda_colonia'  => 'Centro',
                'vivienda_municipio'=> 'Pachuca',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'retiro_directo',
                'monto_credito'     => 450000,
                'subcuenta_vivienda'=> 85000,
                'monto_total_estimado' => 535000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 45000,
                'estado'            => 'en_proceso',
            ],
            [
                'tipo' => $fovissste,  'etapa_idx' => 2,
                'acreditado_nombre' => 'Patricia Guerrero Vidal',
                'acreditado_curp'   => 'GEVP850621MDFRDL09',
                'acreditado_rfc'    => 'GEVP850621QR7',
                'acreditado_telefono' => '7719876543',
                'acreditado_email'  => 'patricia.guerrero@hotmail.com',
                'acreditado_municipio' => 'Tulancingo',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '43600',
                'acreditado_estado_civil' => 'soltero',
                'acreditado_antiguedad_laboral' => 8,
                'vendedor_nombre'   => 'Ernesto Guerrero',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Calle Hidalgo',
                'vivienda_numero'   => '12',
                'vivienda_colonia'  => 'La Hacienda',
                'vivienda_municipio'=> 'Tulancingo',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'compraventa',
                'monto_credito'     => 380000,
                'subcuenta_vivienda'=> 62000,
                'monto_total_estimado' => 442000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 38000,
                'estado'            => 'en_proceso',
            ],
            [
                'tipo' => $fovissste,  'etapa_idx' => 4,
                'acreditado_nombre' => 'Héctor Ramírez Fuentes',
                'acreditado_curp'   => 'RAFH690904HDFMNH02',
                'acreditado_rfc'    => 'RAFH690904MN1',
                'acreditado_telefono' => '7712223344',
                'acreditado_email'  => 'hector.ramirez@yahoo.com',
                'acreditado_municipio' => 'Tizayuca',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '43800',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => 22,
                'vendedor_nombre'   => 'Carmen Fuentes',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Blvd. Tizayuca',
                'vivienda_numero'   => '88',
                'vivienda_colonia'  => 'Villas del Real',
                'vivienda_municipio'=> 'Tizayuca',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'retiro_directo',
                'monto_credito'     => 620000,
                'subcuenta_vivienda'=> 110000,
                'monto_total_estimado' => 730000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 62000,
                'estado'            => 'aprobado',
            ],
            [
                'tipo' => $fovissste,  'etapa_idx' => 6,
                'acreditado_nombre' => 'Silvia Nava Domínguez',
                'acreditado_curp'   => 'NADS750218MDFVML08',
                'acreditado_rfc'    => 'NADS750218PQ5',
                'acreditado_telefono' => '7714455667',
                'acreditado_email'  => 'silvia.nava@gmail.com',
                'acreditado_municipio' => 'Pachuca',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42070',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => 18,
                'vendedor_nombre'   => 'Marco Domínguez',
                'vivienda_tipo'     => 'departamento',
                'vivienda_calle'    => 'Fracc. Las Granjas',
                'vivienda_numero'   => '22-B',
                'vivienda_colonia'  => 'Las Granjas',
                'vivienda_municipio'=> 'Pachuca',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'retiro_directo',
                'monto_credito'     => 510000,
                'subcuenta_vivienda'=> 95000,
                'monto_total_estimado' => 605000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 51000,
                'honorarios_pagados'=> true,
                'estado'            => 'cerrado',
                'fecha_cierre'      => now()->subDays(15)->toDateString(),
            ],
            // INFONAVIT
            [
                'tipo' => $infonavit,  'etapa_idx' => 0,
                'acreditado_nombre' => 'Juan Carlos Flores Ortega',
                'acreditado_curp'   => 'FOOJ881103HDFRLR07',
                'acreditado_rfc'    => 'FOOJ881103ST2',
                'acreditado_telefono' => '7715566778',
                'acreditado_email'  => 'juancarlos.flores@gmail.com',
                'acreditado_municipio' => 'Mineral de la Reforma',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42180',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => 6,
                'vendedor_nombre'   => 'Laura Ortega',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Calle Real del Monte',
                'vivienda_numero'   => '7',
                'vivienda_colonia'  => 'Santa Julia',
                'vivienda_municipio'=> 'Mineral de la Reforma',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'compraventa',
                'monto_credito'     => 290000,
                'subcuenta_vivienda'=> 48000,
                'monto_total_estimado' => 338000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 29000,
                'estado'            => 'en_proceso',
            ],
            [
                'tipo' => $infonavit,  'etapa_idx' => 3,
                'acreditado_nombre' => 'Gabriela Torres Ménez',
                'acreditado_curp'   => 'TOMG920307MDFRRB01',
                'acreditado_rfc'    => 'TOMG920307UV8',
                'acreditado_telefono' => '7716677889',
                'acreditado_email'  => 'gabriela.torres@outlook.com',
                'acreditado_municipio' => 'Tula de Allende',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42800',
                'acreditado_estado_civil' => 'soltero',
                'acreditado_antiguedad_laboral' => 4,
                'vendedor_nombre'   => 'Felipe Méndez',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Av. Allende',
                'vivienda_numero'   => '31',
                'vivienda_colonia'  => 'El Llano',
                'vivienda_municipio'=> 'Tula de Allende',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'retiro_directo',
                'monto_credito'     => 195000,
                'subcuenta_vivienda'=> 35000,
                'monto_total_estimado' => 230000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 19500,
                'estado'            => 'en_proceso',
            ],
            [
                'tipo' => $infonavit,  'etapa_idx' => 6,
                'acreditado_nombre' => 'Ricardo Alvarado Soto',
                'acreditado_curp'   => 'AOSR780415HDFLLC05',
                'acreditado_rfc'    => 'AOSR780415WX3',
                'acreditado_telefono' => '7717788990',
                'acreditado_email'  => 'ricardo.alvarado@gmail.com',
                'acreditado_municipio' => 'Ixmiquilpan',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42300',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => 15,
                'vendedor_nombre'   => 'Norma Soto',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Carr. Ixmiquilpan-Actopan',
                'vivienda_numero'   => 'Km 2',
                'vivienda_colonia'  => 'La Presa',
                'vivienda_municipio'=> 'Ixmiquilpan',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'retiro_directo',
                'monto_credito'     => 340000,
                'subcuenta_vivienda'=> 72000,
                'monto_total_estimado' => 412000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 34000,
                'honorarios_pagados'=> true,
                'estado'            => 'cerrado',
                'fecha_cierre'      => now()->subDays(30)->toDateString(),
            ],
            // COMBO
            [
                'tipo' => $combo,  'etapa_idx' => 1,
                'acreditado_nombre' => 'Alejandro Muñoz Ávila',
                'acreditado_curp'   => 'MUAA830927HDFXVL03',
                'acreditado_rfc'    => 'MUAA830927YZ6',
                'acreditado_telefono' => '7718899001',
                'acreditado_email'  => 'alejandro.munoz@gmail.com',
                'acreditado_municipio' => 'Pachuca',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42030',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => 20,
                'vendedor_nombre'   => 'Isabel Ávila',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Calle Nogal',
                'vivienda_numero'   => '15',
                'vivienda_colonia'  => 'Arboledas',
                'vivienda_municipio'=> 'Pachuca',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'compraventa',
                'monto_credito'     => 780000,
                'subcuenta_vivienda'=> 140000,
                'monto_total_estimado' => 920000,
                'honorarios_porcentaje' => 12,
                'honorarios_monto'  => 93600,
                'estado'            => 'aprobado',
            ],
            [
                'tipo' => $combo,  'etapa_idx' => 4,
                'acreditado_nombre' => 'Verónica Castro Leal',
                'acreditado_curp'   => 'CALV900614MDFSSL02',
                'acreditado_rfc'    => 'CALV900614AB9',
                'acreditado_telefono' => '7719900112',
                'acreditado_email'  => 'veronica.castro@yahoo.com',
                'acreditado_municipio' => 'Apan',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '43900',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => 10,
                'vendedor_nombre'   => 'Ernesto Leal',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Prolongación Zaragoza',
                'vivienda_numero'   => '58',
                'vivienda_colonia'  => 'Nueva Apan',
                'vivienda_municipio'=> 'Apan',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'retiro_directo',
                'monto_credito'     => 650000,
                'subcuenta_vivienda'=> 115000,
                'monto_total_estimado' => 765000,
                'honorarios_porcentaje' => 12,
                'honorarios_monto'  => 78000,
                'estado'            => 'firmado',
            ],
            // AVALÚO
            [
                'tipo' => $avaluo,  'etapa_idx' => 0,
                'acreditado_nombre' => 'Fernando Báez Jiménez',
                'acreditado_curp'   => 'BAJF870222HDFRML08',
                'acreditado_rfc'    => 'BAJF870222CD4',
                'acreditado_telefono' => '7720011223',
                'acreditado_email'  => 'fernando.baez@gmail.com',
                'acreditado_municipio' => 'Actopan',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42500',
                'acreditado_estado_civil' => 'soltero',
                'acreditado_antiguedad_laboral' => 5,
                'vendedor_nombre'   => null,
                'vivienda_tipo'     => 'terreno',
                'vivienda_calle'    => 'Camino a Tepejí',
                'vivienda_numero'   => 'S/N',
                'vivienda_colonia'  => 'El Arenal',
                'vivienda_municipio'=> 'Actopan',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'otro',
                'monto_credito'     => 0,
                'honorarios_porcentaje' => 0,
                'honorarios_monto'  => 3500,
                'estado'            => 'en_proceso',
            ],
            [
                'tipo' => $avaluo,  'etapa_idx' => 2,
                'acreditado_nombre' => 'Margarita Reyes Contreras',
                'acreditado_curp'   => 'RECM650930MDFYRR04',
                'acreditado_rfc'    => 'RECM650930EF7',
                'acreditado_telefono' => '7721122334',
                'acreditado_email'  => 'margarita.reyes@hotmail.com',
                'acreditado_municipio' => 'Huejutla',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '43000',
                'acreditado_estado_civil' => 'viudo',
                'acreditado_antiguedad_laboral' => null,
                'vendedor_nombre'   => null,
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Av. Insurgentes',
                'vivienda_numero'   => '102',
                'vivienda_colonia'  => 'Centro',
                'vivienda_municipio'=> 'Huejutla',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'otro',
                'monto_credito'     => 0,
                'honorarios_porcentaje' => 0,
                'honorarios_monto'  => 3500,
                'honorarios_pagados'=> true,
                'estado'            => 'cerrado',
                'fecha_cierre'      => now()->subDays(10)->toDateString(),
            ],
            // ESCRITURAS
            [
                'tipo' => $escrituras,  'etapa_idx' => 1,
                'acreditado_nombre' => 'Edmundo Peña Garza',
                'acreditado_curp'   => 'PEGE720804HDFRLM09',
                'acreditado_rfc'    => 'PEGE720804GH2',
                'acreditado_telefono' => '7722233445',
                'acreditado_email'  => 'edmundo.pena@gmail.com',
                'acreditado_municipio' => 'Tizayuca',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '43800',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => null,
                'vendedor_nombre'   => null,
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Privada del Sol',
                'vivienda_numero'   => '3',
                'vivienda_colonia'  => 'Los Laureles',
                'vivienda_municipio'=> 'Tizayuca',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'otro',
                'monto_credito'     => 0,
                'honorarios_porcentaje' => 0,
                'honorarios_monto'  => 8000,
                'estado'            => 'en_proceso',
            ],
            [
                'tipo' => $escrituras,  'etapa_idx' => 3,
                'acreditado_nombre' => 'Concepción Luna Bravo',
                'acreditado_curp'   => 'LUBC800115MDFNRN06',
                'acreditado_rfc'    => 'LUBC800115IJ3',
                'acreditado_telefono' => '7723344556',
                'acreditado_email'  => 'concepcion.luna@gmail.com',
                'acreditado_municipio' => 'Mixquiahuala',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42700',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => null,
                'vendedor_nombre'   => null,
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Calle Morelos',
                'vivienda_numero'   => '27',
                'vivienda_colonia'  => 'Centro',
                'vivienda_municipio'=> 'Mixquiahuala',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'otro',
                'monto_credito'     => 0,
                'honorarios_porcentaje' => 0,
                'honorarios_monto'  => 8000,
                'honorarios_pagados'=> true,
                'estado'            => 'cerrado',
                'fecha_cierre'      => now()->subDays(45)->toDateString(),
            ],
            // FOVISSSTE adicionales
            [
                'tipo' => $fovissste,  'etapa_idx' => 1,
                'acreditado_nombre' => 'Rogelio Santos Ibáñez',
                'acreditado_curp'   => 'SAIR760530HDFNBG01',
                'acreditado_rfc'    => 'SAIR760530KL5',
                'acreditado_telefono' => '7724455667',
                'acreditado_email'  => 'rogelio.santos@gmail.com',
                'acreditado_municipio' => 'Pachuca',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42090',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => 14,
                'vendedor_nombre'   => 'Alicia Ibáñez',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Blvd. Valle de San Javier',
                'vivienda_numero'   => '301',
                'vivienda_colonia'  => 'Valle de San Javier',
                'vivienda_municipio'=> 'Pachuca',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'retiro_directo',
                'monto_credito'     => 520000,
                'subcuenta_vivienda'=> 98000,
                'monto_total_estimado' => 618000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 52000,
                'estado'            => 'pausado',
            ],
            [
                'tipo' => $fovissste,  'etapa_idx' => 3,
                'acreditado_nombre' => 'Elena Vargas Espinosa',
                'acreditado_curp'   => 'VAEE910808MDFRRL05',
                'acreditado_rfc'    => 'VAEE910808MN0',
                'acreditado_telefono' => '7725566778',
                'acreditado_email'  => 'elena.vargas@hotmail.com',
                'acreditado_municipio' => 'Tepeapulco',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '43980',
                'acreditado_estado_civil' => 'soltero',
                'acreditado_antiguedad_laboral' => 9,
                'vendedor_nombre'   => 'Gustavo Espinosa',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Calle Independencia',
                'vivienda_numero'   => '14',
                'vivienda_colonia'  => 'Constitución',
                'vivienda_municipio'=> 'Tepeapulco',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'compraventa',
                'monto_credito'     => 410000,
                'subcuenta_vivienda'=> 78000,
                'monto_total_estimado' => 488000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 41000,
                'estado'            => 'en_proceso',
            ],
            [
                'tipo' => $infonavit,  'etapa_idx' => 2,
                'acreditado_nombre' => 'Bernardo Aguilar Téllez',
                'acreditado_curp'   => 'AUTB841212HDFGLR06',
                'acreditado_rfc'    => 'AUTB841212OP1',
                'acreditado_telefono' => '7726677889',
                'acreditado_email'  => 'bernardo.aguilar@gmail.com',
                'acreditado_municipio' => 'Zimapán',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42330',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => 7,
                'vendedor_nombre'   => 'Susana Téllez',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Carr. Zimapán-Jacala',
                'vivienda_numero'   => 'KM 1',
                'vivienda_colonia'  => 'La Loma',
                'vivienda_municipio'=> 'Zimapán',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'retiro_directo',
                'monto_credito'     => 260000,
                'subcuenta_vivienda'=> 44000,
                'monto_total_estimado' => 304000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 26000,
                'estado'            => 'en_proceso',
            ],
            [
                'tipo' => $fovissste,  'etapa_idx' => 5,
                'acreditado_nombre' => 'Norma Alicia Paz Rivera',
                'acreditado_curp'   => 'PARN680720MDFZVR02',
                'acreditado_rfc'    => 'PARN680720QR8',
                'acreditado_telefono' => '7727788990',
                'acreditado_email'  => 'norma.paz@gmail.com',
                'acreditado_municipio' => 'Tulancingo',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '43600',
                'acreditado_estado_civil' => 'divorciado',
                'acreditado_antiguedad_laboral' => 25,
                'vendedor_nombre'   => 'Ramón Rivera',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Calle 2 de Abril',
                'vivienda_numero'   => '9',
                'vivienda_colonia'  => 'Loma Bonita',
                'vivienda_municipio'=> 'Tulancingo',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'retiro_directo',
                'monto_credito'     => 590000,
                'subcuenta_vivienda'=> 105000,
                'monto_total_estimado' => 695000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 59000,
                'estado'            => 'firmado',
            ],
            [
                'tipo' => $combo,  'etapa_idx' => 0,
                'acreditado_nombre' => 'Jesús Moreno Rueda',
                'acreditado_curp'   => 'MORJ950314HDFRLS09',
                'acreditado_rfc'    => 'MORJ950314ST4',
                'acreditado_telefono' => '7728899001',
                'acreditado_email'  => 'jesus.moreno@gmail.com',
                'acreditado_municipio' => 'Pachuca',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42160',
                'acreditado_estado_civil' => 'soltero',
                'acreditado_antiguedad_laboral' => 3,
                'vendedor_nombre'   => 'Esperanza Rueda',
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Av. Revolución',
                'vivienda_numero'   => '77',
                'vivienda_colonia'  => 'Cubitos',
                'vivienda_municipio'=> 'Pachuca',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'compraventa',
                'monto_credito'     => 820000,
                'subcuenta_vivienda'=> 155000,
                'monto_total_estimado' => 975000,
                'honorarios_porcentaje' => 12,
                'honorarios_monto'  => 98400,
                'estado'            => 'en_proceso',
            ],
            [
                'tipo' => $infonavit,  'etapa_idx' => 5,
                'acreditado_nombre' => 'Liliana Pacheco Vega',
                'acreditado_curp'   => 'PAVL861019MDFCGL07',
                'acreditado_rfc'    => 'PAVL861019UV5',
                'acreditado_telefono' => '7729900112',
                'acreditado_email'  => 'liliana.pacheco@outlook.com',
                'acreditado_municipio' => 'Mineral de la Reforma',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42186',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => 11,
                'vendedor_nombre'   => 'Tomás Vega',
                'vivienda_tipo'     => 'departamento',
                'vivienda_calle'    => 'Blvd. Colosio',
                'vivienda_numero'   => '450-4B',
                'vivienda_colonia'  => 'Ciudad de los Niños',
                'vivienda_municipio'=> 'Mineral de la Reforma',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'compraventa',
                'monto_credito'     => 315000,
                'subcuenta_vivienda'=> 52000,
                'monto_total_estimado' => 367000,
                'honorarios_porcentaje' => 10,
                'honorarios_monto'  => 31500,
                'estado'            => 'aprobado',
            ],
            [
                'tipo' => $escrituras,  'etapa_idx' => 2,
                'acreditado_nombre' => 'Alfonso Quiroz Medina',
                'acreditado_curp'   => 'QUMA710628HDFRDL03',
                'acreditado_rfc'    => 'QUMA710628WX6',
                'acreditado_telefono' => '7730011223',
                'acreditado_email'  => 'alfonso.quiroz@gmail.com',
                'acreditado_municipio' => 'Atotonilco el Grande',
                'acreditado_estado' => 'Hidalgo',
                'acreditado_cp'     => '42060',
                'acreditado_estado_civil' => 'casado',
                'acreditado_antiguedad_laboral' => null,
                'vendedor_nombre'   => null,
                'vivienda_tipo'     => 'casa',
                'vivienda_calle'    => 'Carr. Nacional',
                'vivienda_numero'   => '18',
                'vivienda_colonia'  => 'Centro',
                'vivienda_municipio'=> 'Atotonilco el Grande',
                'vivienda_estado'   => 'Hidalgo',
                'uso_credito'       => 'otro',
                'monto_credito'     => 0,
                'honorarios_porcentaje' => 0,
                'honorarios_monto'  => 9500,
                'estado'            => 'en_proceso',
            ],
        ];

        $asesorIndex = 0;
        $totalAsesores = count($asesores);

        foreach ($expedientesData as $data) {
            $tipo     = $data['tipo'];
            $etapas   = $etapasMap[$tipo->id] ?? [];
            $etapaIdx = min($data['etapa_idx'], count($etapas) - 1);
            $etapaId  = $etapas[$etapaIdx] ?? $etapas[0];

            // Rota asesores de forma distribuida
            $asesorId = $asesores[$asesorIndex % $totalAsesores];
            $asesorIndex++;

            // Evitar duplicado por acreditado_curp
            $exists = Expediente::where('acreditado_curp', $data['acreditado_curp'])->exists();
            if ($exists) continue;

            $año  = now()->year;
            $last = Expediente::whereYear('created_at', $año)->count() + 1;
            $folio = 'EXP-' . $año . '-' . str_pad($last, 4, '0', STR_PAD_LEFT);

            Expediente::create([
                'folio'                       => $folio,
                'tipo_tramite_id'             => $tipo->id,
                'etapa_tramite_id'            => $etapaId,
                'asesor_id'                   => $asesorId,
                'contacto_id'                 => null,
                'estado'                      => $data['estado'],
                'acreditado_nombre'           => $data['acreditado_nombre'],
                'acreditado_curp'             => $data['acreditado_curp'],
                'acreditado_rfc'              => $data['acreditado_rfc'],
                'acreditado_telefono'         => $data['acreditado_telefono'],
                'acreditado_email'            => $data['acreditado_email'],
                'acreditado_municipio'        => $data['acreditado_municipio'],
                'acreditado_estado'           => $data['acreditado_estado'],
                'acreditado_cp'               => $data['acreditado_cp'],
                'acreditado_estado_civil'     => $data['acreditado_estado_civil'],
                'acreditado_antiguedad_laboral' => $data['acreditado_antiguedad_laboral'],
                'vendedor_nombre'             => $data['vendedor_nombre'] ?? null,
                'vivienda_tipo'               => $data['vivienda_tipo'],
                'vivienda_calle'              => $data['vivienda_calle'],
                'vivienda_numero'             => $data['vivienda_numero'],
                'vivienda_colonia'            => $data['vivienda_colonia'],
                'vivienda_municipio'          => $data['vivienda_municipio'],
                'vivienda_estado'             => $data['vivienda_estado'],
                'uso_credito'                 => $data['uso_credito'],
                'monto_credito'               => $data['monto_credito'] ?? 0,
                'subcuenta_vivienda'          => $data['subcuenta_vivienda'] ?? null,
                'monto_total_estimado'        => $data['monto_total_estimado'] ?? null,
                'honorarios_porcentaje'       => $data['honorarios_porcentaje'],
                'honorarios_monto'            => $data['honorarios_monto'],
                'honorarios_pagados'          => $data['honorarios_pagados'] ?? false,
                'total_gastos_financiados'    => 0,
                'fecha_apertura'              => now()->subDays(rand(10, 120))->toDateString(),
                'fecha_cierre'                => $data['fecha_cierre'] ?? null,
            ]);

            // Generar comisión automáticamente para expedientes cerrados
            if (($data['estado'] ?? '') === 'cerrado' && ($data['honorarios_monto'] ?? 0) > 0) {
                $existe = \App\Models\Comision::where('expediente_id', $expediente->id)->exists();
                if (! $existe) {
                    $montoComision = 10000; // $10,000 MXN fijo por cierre
                    \App\Models\Comision::firstOrCreate(
                        ['expediente_id' => $expediente->id],
                        [
                            'asesor_id'           => $expediente->asesor_id,
                            'monto_base'          => $data['honorarios_monto'],
                            'porcentaje_comision' => 0,
                            'monto_comision'      => $montoComision,
                            'estado'              => 'pendiente',
                            'fecha_generacion'    => $data['fecha_cierre'] ?? now()->toDateString(),
                        ]
                    );
                }
            }
        }

        $total = Expediente::count();
        $comTotal = \App\Models\Comision::count();
        $this->command->info("✓ {$total} expedientes y {$comTotal} comisiones de prueba creados.");
    }
}
