version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: laravel-app
    ports:
      - "8000"
    volumes:
      - storage:/var/www/html/storage
    networks:
      - dokploy
    command: >
      sh -c "php artisan storage:link || true &&
             php artisan migrate --force &&
             php artisan config:cache &&
             php artisan route:cache &&
             php artisan view:cache &&
             php artisan serve --host=0.0.0.0 --port=8000"

volumes:
  storage:

networks:
  dokploy:
    external: true
