version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: laravel-app
    ports:
      - "8000"
    volumes:
      - storage:/var/www/html/storage
    networks:
      - dokploy


volumes:
  storage:

networks:
  dokploy:
    external: true
